export const iconsTable: any = {
  Antigüedad: 'calendar-alt',
  Baños: 'bath',
  Dormitorios: 'bed',
  'Medio Baños': 'toilet',
  'Metraje Construido': 'ruler-combined',
  'Metraje Total': 'ruler-combined',
  Parqueaderos: 'car',
  'Valor Alicuota': 'money-bill',
  'A estrenar': 'star',
  'Areas húmedas': 'tint',
  Bodega: 'box',
  'Cerca de parque': 'tree',
  'Uso De Suelo': 'wrench',
  Altura: 'ruler-vertical',
  Frente: 'ruler-horizontal',
  Pendiente: 'ruler',
  Cine: 'video',
  'Dentro de Urbanización': 'building',
  Gimnasio: 'dumbbell',
  'Juegos Infantiles': 'football-ball',
  'Parqueadero visitas': 'car',
  'Pet Friendly': 'dog',
  Piscina: 'swimmer',
  'Seguridad Privada': 'video',
  'Terraza/Balcón': 'leaf',
  'Valor Alicuota incluido en Valor de Arriendo?': 'money-bill',
  '# Pisos permitidos': 'building',
  'COS PB': 'money-bill',
  'COS Total': 'money-bill',
  'Zona BBQ': 'fire',
  'Vocación de Suelo': 'tractor',
  'Area de Carga y descarga': 'truck',
  Ciudad: 'map-marker-alt',
  Provincia: 'map-marker-alt',
  Sector: 'map-marker-alt',
  Dirección: 'map',
  Transacción: 'handshake',
  Luz: 'lightbulb',
  Forma: 'shapes',
  'Vias De Acceso': 'road',
  'Precio ': 'dollar-sign',
  Tipo: 'home',
  'Medios Baños': 'toilet'
};
